IN-266 :: No Requirement On Section Always Displayed
valispace/ValispaceGoogleDocsAddon pull request #17
Opened 2022-05-19 17:41 UTC by xernobyl

2022-06-08 09:44 UTC, antopemo approved these changes
LGTM

2022-06-09 08:23 UTC, cauenapier requested changes
@franciscoatsantos I tested with an empty section and the "no requirements in section" didn't appear.
![image](https://user-images.githubusercontent.com/17514058/172800590-45c91549-4f3d-416f-b19b-3d1b17dac3c0.png)

2022-06-09 11:20 UTC, antopemo requested changes

2022-06-09 11:20 UTC, antopemo commented on src/frontend/requirements/requirements_.js
> +        section_inserted = true;
This boolean needs to go on line 173 before the if. That is when the section has been inserted and where you can measure after in 182 if it has been inserted

2022-06-09 15:27 UTC, merged